### ISSUE TITLE
Openslide integration is broken with the latest version of libvips

### ISSUE THREAD

**Issue by EKami** [conda-forge/libvips-feedstock#129]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

I noticed this morning that my code was crashing after updating my dependencies, and the issue pointed to the function `pyvips.Image.openslideload` not being found.
After investigation, it seems the libvips packages were recently updated in Anaconda/conda-forge ([linux-64/libvips-8.16.0-hbdc070c_5.conda](https://anaconda.org/conda-forge/libvips/8.16.0/download/linux-64/libvips-8.16.0-hbdc070c_5.conda)) but the version remained the same (8.16.0).

This new build, however, does not seem to ship with support for OpenSlide.
To reproduce, one can use the following `pixi.toml` ([link to pixi](https://pixi.sh/latest/)):
```
[project]
channels = ["conda-forge"]
description = "Test env"
name = "test"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
python = "3.12.*"
libvips = { version = "8.16.0", build = "hbdc070c_5" }
pyvips = "*"
```
Then run `pixi run python -c 'import pyvips; print(pyvips.type_find("VipsForeignLoad", "openslideload"))'`, you'll get `0`.
However with the following:
```
[project]
channels = ["conda-forge"]
description = "Test env"
name = "test"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
python = "3.12.*"
libvips = { version = "8.16.0", build = "hfd0f9a2_2" }
pyvips = "*"
```
The output will be different from 0.

### Installed packages

```shell
Check the reproducibility steps above
```

### Environment info

```shell
Check the reproducibility steps above
```

**Comment by hmaarrfk** [comment]
Indeed it seems that the logs show:
```
WARNING (libvips): run-exports library package conda-forge/linux-64::openslide==4.0.0=h58ba908_1 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
```

ps. i still don't use pixi, so it is hard for me to repro with what you gave.

To our tests, should we add

```
python -c 'assert pyvips.type_find("VipsForeignLoad", "openslideload")'
```

it might have been due to the migration to openslide 4.

do you have the skills to try to contribute a fix?

**Comment by hmaarrfk** [comment]
it might have been easier than i thought.

for others

```
python build_locally.py --debug
# then 
pkg-config --debug --exists openslide
```

i added a force enabled on the meson options, so it won' happen again. I also added the python test at the end.

**Comment by EKami** [comment]
Thanks for the fix :)

**Comment by hmaarrfk** [comment]
Thanks for raising the issue a clear instructions and making the problem obvious!
