### ISSUE TITLE
Tests being skipped for ppc64le

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/libvips-feedstock#55]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I decided to skip the tests for ppc64le because I think they are due to emulation.

We could be a little more selective about it.

### Installed packages

```shell
see log
```

### Environment info

```shell
see log
```

**Comment by hmaarrfk** [comment]
[32_log.txt](https://github.com/conda-forge/libvips-feedstock/files/8312013/32_log.txt)

**Comment by kleisauke** [comment]
Could issue https://github.com/libvips/libvips/issues/2404 be relevant here? [The fix](https://gitlab.freedesktop.org/gstreamer/orc/-/commit/d8b81c2e35854dd84e99065d3a16d4183b27f916) for that orc bug is unfortunately not available in any released version.

You could try setting the `VIPS_NOVECTOR=1` environment variable to check if you are affected by that bug.

**Comment by hmaarrfk** [comment]
We could patch orc if yo uwant. Either way, feel free to make a PR. I'm not super vested in PPC64le and it seems that most people have pretty narrow usecaes (we haven't seen terrible consequences of not testing certain things yet).

**Comment by kleisauke** [comment]
I just opened PR #79 for this now that the above mentioned fix has been landed in orc v0.4.33.
